<?xml version="1.0"?>
<robot xmlns:xacro="http://www.ros.org/wiki/xacro" name="opportunity_rover">

  <xacro:include filename="$(find rover_arm_pkg)/urdf/rover_arm.xacro" />

  <xacro:property name="chassis_len" value="0.50" />
  <xacro:property name="chassis_width" value="0.30" />
  <xacro:property name="chassis_height" value="0.15" />
  
  <xacro:property name="wheel_radius" value="0.06" />
  <xacro:property name="wheel_width" value="0.04" />
  
  <xacro:property name="wheel_x_offset" value="0.22" /> <xacro:property name="wheel_y_offset" value="0.20" /> <xacro:property name="middle_wheel_x" value="0.0" />  <xacro:property name="mast_height" value="0.40" />

  <material name="black">
    <color rgba="0.1 0.1 0.1 1.0"/>
  </material>
  <material name="gold"> <color rgba="0.8 0.7 0.1 1.0"/>
  </material>
  <material name="blue">
    <color rgba="0.0 0.0 0.8 1.0"/>
  </material>

  <xacro:macro name="steering_link" params="prefix parent x y reflect_y">
    <link name="${prefix}_steering_link">
      <visual>
        <geometry>
          <box size="0.05 0.05 0.05"/>
        </geometry>
        <material name="grey"/>
      </visual>
    </link>

    <joint name="${prefix}_steering_joint" type="revolute">
      <parent link="${parent}"/>
      <child link="${prefix}_steering_link"/>
      <origin xyz="${x} ${y * reflect_y} -0.05" rpy="0 0 0"/>
      <axis xyz="0 0 1"/> <limit lower="-0.785" upper="0.785" effort="10" velocity="1.0"/> </joint>
  </xacro:macro>

  <xacro:macro name="wheel_link" params="prefix parent is_steering">
    <link name="${prefix}_wheel">
      <visual>
        <geometry>
          <cylinder radius="${wheel_radius}" length="${wheel_width}"/>
        </geometry>
        <origin xyz="0 0 0" rpy="1.5708 0 0"/> <material name="black"/>
      </visual>
      <collision>
        <geometry>
          <cylinder radius="${wheel_radius}" length="${wheel_width}"/>
        </geometry>
        <origin xyz="0 0 0" rpy="1.5708 0 0"/>
      </collision>
    </link>

    <joint name="${prefix}_wheel_joint" type="continuous">
      <parent link="${parent}"/>
      <child link="${prefix}_wheel"/>
      
      <xacro:if value="${is_steering}">
        <origin xyz="0 0 -0.05" rpy="0 0 0"/>
      </xacro:if>
      <xacro:unless value="${is_steering}">
        <origin xyz="0 0.05 0" rpy="0 0 0"/> </xacro:unless>
      
      <axis xyz="0 1 0"/> </joint>
  </xacro:macro>

  <link name="base_footprint"/>

  <joint name="base_joint" type="fixed">
    <parent link="base_footprint"/>
    <child link="base_link"/>
    <origin xyz="0 0 ${wheel_radius + 0.10}" rpy="0 0 0"/>
  </joint>

  <link name="base_link">
    <visual>
      <geometry>
        <box size="${chassis_len} ${chassis_width} ${chassis_height}"/>
      </geometry>
      <material name="gold"/>
    </visual>
    <collision>
      <geometry>
        <box size="${chassis_len} ${chassis_width} ${chassis_height}"/>
      </geometry>
    </collision>
  </link>

  <xacro:steering_link prefix="fl" parent="base_link" x="${wheel_x_offset}" y="${wheel_y_offset}" reflect_y="1" />
  <xacro:wheel_link prefix="fl" parent="fl_steering_link" is_steering="true" />

  <xacro:steering_link prefix="fr" parent="base_link" x="${wheel_x_offset}" y="${wheel_y_offset}" reflect_y="-1" />
  <xacro:wheel_link prefix="fr" parent="fr_steering_link" is_steering="true" />

  <xacro:steering_link prefix="rl" parent="base_link" x="-${wheel_x_offset}" y="${wheel_y_offset}" reflect_y="1" />
  <xacro:wheel_link prefix="rl" parent="rl_steering_link" is_steering="true" />

  <xacro:steering_link prefix="rr" parent="base_link" x="-${wheel_x_offset}" y="${wheel_y_offset}" reflect_y="-1" />
  <xacro:wheel_link prefix="rr" parent="rr_steering_link" is_steering="true" />

  <joint name="ml_bogie_joint" type="fixed">
    <parent link="base_link"/>
    <child link="ml_bogie"/>
    <origin xyz="0 ${wheel_y_offset} -0.05" rpy="0 0 0"/>
  </joint>
  <link name="ml_bogie"/>
  <xacro:wheel_link prefix="ml" parent="ml_bogie" is_steering="false" />

  <joint name="mr_bogie_joint" type="fixed">
    <parent link="base_link"/>
    <child link="mr_bogie"/>
    <origin xyz="0 -${wheel_y_offset} -0.05" rpy="0 0 0"/>
  </joint>
  <link name="mr_bogie"/>
  <xacro:wheel_link prefix="mr" parent="mr_bogie" is_steering="false" />

  <link name="mast_link">
    <visual>
      <geometry>
        <cylinder radius="0.02" length="${mast_height}"/>
      </geometry>
      <material name="grey"/>
    </visual>
  </link>

  <joint name="mast_joint" type="fixed">
    <parent link="base_link"/>
    <child link="mast_link"/>
    <origin xyz="0.15 0 ${chassis_height/2 + mast_height/2}" rpy="0 0 0"/>
  </joint>

  <link name="camera_link">
    <visual>
      <geometry>
        <box size="0.05 0.18 0.05"/> </geometry>
      <material name="black"/>
    </visual>
  </link>

  <joint name="camera_joint" type="fixed">
    <parent link="mast_link"/>
    <child link="camera_link"/>
    <origin xyz="0.02 0 ${mast_height/2}" rpy="0 0 0"/>
  </joint>

  <link name="laser">
    <visual>
      <geometry>
        <cylinder radius="0.035" length="0.04"/>
      </geometry>
      <material name="blue"/>
    </visual>
  </link>

  <joint name="laser_joint" type="fixed">
    <parent link="base_link"/>
    <child link="laser"/>
    <origin xyz="0 0 ${chassis_height/2 + 0.02}" rpy="0 0 0"/>
  </joint>

  <joint name="arm_mount_joint" type="fixed">
    <parent link="base_link"/>
    <child link="arm_base_link"/> <origin xyz="${chassis_len/2} 0 0" rpy="0 0 0"/> </joint>

</robot>
